theme: jekyll-theme-minimal
title: Нанять Желнова
description: Систематические обзоры, scoping-обзоры, синтез доказательств. Дизайн исследований, базы данных, статистический анализ. Редактирование и перевод научных текстов.
show_downloads: true
google_analytics: UA-122303329-2
