theme: jekyll-theme-minimal
timezone: Etc/GMT+12
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
title: "Doctor Zhelnov"
url: "https://drzhelnov.github.io/"
description: "Pavel Zhelnov, MD, quit a career in orthopedic spine surgery due to dermatitis, transitioned to health policy & evidence synthesis, and is exploring machine learning & Web3."
lang: "en-US"
show_downloads: true
google_analytics: UA-122303329-2
markdown: kramdown
plugins:
  - jekyll-readme-index
  - jekyll-seo-tag
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
optional_front_matter:
  remove_originals: false
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
