theme: jekyll-theme-minimal
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
title: "Доктор Желнов"
url: "https://drzhelnov.com/"
description: "Медицинский английский, USMLE. Дизайн научных исследований, базы данных, статистический анализ. Синтез доказательств (литобзор): систематический обзор литературы, литературный обзор предметного поля (scoping review)."
show_downloads: true
google_analytics: UA-122303329-2
markdown: kramdown
plugins:
  - jekyll-readme-index
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
