theme: jekyll-theme-minimal
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "old/nov2021"
    values:
      layout: "old-nov2021" # overrides previous default layout
      strip_title: true
  -
    scope:
      path: "usmle"
    values:
      layout: "old-nov2021" # overrides previous default layout
      strip_title: true
  -
    scope:
      path: "jobs"
    values:
      layout: "old-mar2023" # overrides previous default layout
      strip_title: true
title: "Doctor Zhelnov"

url: "https://drzhelnov.com/"
description: "Personal website of Pavel Zhelnov, MD"
old:
  nov2021:
    title: "Доктор Желнов"
    description: "Медицинский английский, USMLE. Дизайн научных исследований, базы данных, статистический анализ. Синтез доказательств (литобзор): систематический обзор литературы, литературный обзор предметного поля (scoping review)."

show_downloads: true
google_analytics: UA-122303329-2
markdown: kramdown
plugins:
  - jekyll-readme-index
  - jekyll-seo-tag
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
optional_front_matter:
  remove_originals: false
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
csv_reader:
    converters:
      - numeric
    headers: true
    encoding: utf-8
sass:
    load_paths: 
        - _sass
