theme: jekyll-theme-minimal
title: Нанять Желнова
description: Дизайн исследований, базы данных, презентация и статистический анализ, написание и публикация научных докладов.
show_downloads: true
google_analytics: UA-122303329-2
